### ISSUE TITLE
Kong unable to load js plugin

### ISSUE THREAD

**Issue by esatterwhite** [Kong/kong-js-pdk#82]
Trying to load a simple plugin as an experiment, but kong is always crashing when trying to introspect the plug and isn't apparently obvious as to why 

```shell
ingress-kong-8f894f697-8g5qb kong-proxy nginx: [error] init_by_lua error: ...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:159: Not a plugin info table: 
ingress-kong-8f894f697-8g5qb kong-proxy /usr/local/bin/kong-js-pluginserver --plugins-directory /home/kong/plugins --dump-all-plugins
ingress-kong-8f894f697-8g5qb kong-proxy plugin loaded
ingress-kong-8f894f697-8g5qb kong-proxy [{"Name":"fake","Version":"1.0.0","Phases":["access"],"Priority":0,"Schema":{"name":"fake","fields":[{"config":{"type":"record","fields":[{"header":{"type":"string"}}]}}]}}]
ingress-kong-8f894f697-8g5qb kong-proxy 
ingress-kong-8f894f697-8g5qb kong-proxy stack traceback:
ingress-kong-8f894f697-8g5qb kong-proxy         [C]: in function 'error'
ingress-kong-8f894f697-8g5qb kong-proxy         ...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:159: in function 'ask_info'
ingress-kong-8f894f697-8g5qb kong-proxy         ...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:195: in function 'get_plugin_info'
ingress-kong-8f894f697-8g5qb kong-proxy         ...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:262: in function 'get_plugin'
ingress-kong-8f894f697-8g5qb kong-proxy         ...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:270: in function 'load_plugin'
ingress-kong-8f894f697-8g5qb kong-proxy         /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:136: in function 'load_plugin_handler'
ingress-kong-8f894f697-8g5qb kong-proxy         /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:221: in function 'load_plugin'
ingress-kong-8f894f697-8g5qb kong-proxy         /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:273: in function 'load_plugin_schemas'
ingress-kong-8f894f697-8g5qb kong-proxy         /usr/local/share/lua/5.1/kong/init.lua:515: in function 'init'
ingress-kong-8f894f697-8g5qb kong-proxy         init_by_lua:3: in main chunk
```

### Kong Config

```yaml
 - name: KONG_PLUGINS
   value: bundled,fake
 - name: KONG_PLUGINSERVER_NAMES
   value: js
 - name: KONG_PLUGINSERVER_JS_SOCKET
   value: /usr/local/kong/js_pluginserver.sock
 - name: KONG_PLUGINSERVER_JS_START_CMD
   value: /usr/local/bin/kong-js-pluginserver --plugins-directory /home/kong/plugins
 - name: KONG_PLUGINSERVER_JS_QUERY_CMD
   value: /usr/local/bin/kong-js-pluginserver --plugins-directory /home/kong/plugins --dump-all-plugins
```

### Plugin Directory

```txl
plugins/
├── fake.js
├── package.json
└── package-lock.json
```

### Plugin Code

```javascript
'use strict'

const uuid = require('uuid')
const {version: Version} = require('./package.json')

class Plugin {
  constructor(config = {}) {
    this.config = config
    this.header = config.header || 'X-Request-ID'
  }

  async access(kong) {
    await kong.response.set_header(this.header, uuid())
  }
}
console.log('plugin loaded')
module.exports = {
  Plugin
, Version
, Priority: 0
, Schema: [
    {header: { type: "string" }}
  ]
}
```
### Plugin Config

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
plugin: fake
metadata:
  name: fake-id
config:
  header: 'X-Fake-ID-1'
```
